name: Unit Tests - MacOS
on:
# manual trigger
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: macos-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build and test
      run: |
        dotnet test -c Release ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
